import Foundation

/// Tabla de texto para un idioma. Se accede por clave, y una prueba comprueba que ningún
/// idioma deje claves fuera.
public struct Strings: Sendable {
    public let language: Language
    private let table: [TextKey: String]

    public subscript(_ key: TextKey) -> String {
        table[key] ?? key.rawValue
    }

    /// Para los textos que llevan `%@`.
    public func callAsFunction(_ key: TextKey, _ arguments: CVarArg...) -> String {
        String(format: self[key], arguments: arguments)
    }

    public static func table(for language: Language) -> Strings {
        Strings(language: language, table: language == .spanish ? spanishTable : englishTable)
    }

    /// Expuesta para que las pruebas comprueben la cobertura de claves.
    public static func rawTable(for language: Language) -> [TextKey: String] {
        language == .spanish ? spanishTable : englishTable
    }

    private static let spanishTable: [TextKey: String] = [
        .tabPrograms: "Programas",
        .tabArchives: "Comprimidos",
        .toolWine: "Wine",
        .toolExtractor: "Extractor",
        .toolNotInstalled: "sin instalar",
        .languageMenu: "Idioma",

        .menuTools: "Herramientas",
        .menuRefresh: "Volver a buscar herramientas",
        .menuInstallExtractors: "Instalar los extractores",
        .menuFindWine: "Buscar Wine a mano…",
        .menuForgetWine: "Olvidar el Wine elegido",
        .menuUnblockWine: "Desbloquear Wine",
        .menuResetWindows: "Restablecer Windows",
        .menuOpenWindowsFolder: "Abrir la carpeta de Windows",
        .menuOpenProgram: "Abrir programa de Windows…",
        .menuOpenArchive: "Abrir comprimido…",
        .menuCopyActivity: "Copiar la actividad",
        .menuClearActivity: "Limpiar la actividad",

        .dropProgramTitle: "Suelta aquí un programa de Windows",
        .dropProgramSubtitle: "Archivos .exe y .msi. También puedes pulsar para buscarlo.",
        .dropArchiveTitle: "Suelta aquí un archivo comprimido",
        .dropArchiveSubtitle: "Archivos .rar, .zip, .7z, .tar, .iso. También puedes pulsar para buscarlo.",

        .revealInFinder: "Mostrar en el Finder",
        .removeFile: "Quitar el archivo",
        .chooseAnotherProgram: "Elegir otro programa",
        .chooseAnotherArchive: "Elegir otro comprimido",

        .saveIn: "Guardar en",
        .change: "Cambiar",
        .automatic: "Automático",
        .ownFolder: "Carpeta propia",
        .ownFolderHint: "Con el nombre del comprimido",
        .password: "Contraseña",
        .passwordHint: "Solo si la pide",
        .passwordNone: "Ninguna",
        .ifExists: "Si ya existe",
        .whenDone: "Al terminar",
        .whenDoneHint: "Abrir en el Finder",
        .policySkip: "Conservar los existentes",
        .policyRename: "Renombrar los nuevos",
        .policyOverwrite: "Sobrescribir",
        .policySkipWhy: "Si un archivo ya está en la carpeta, se deja como está.",
        .policyRenameWhy: "Los archivos repetidos se guardan con otro nombre.",
        .policyOverwriteWhy: "Los archivos repetidos se reemplazan por los del comprimido.",

        .extract: "Extraer",
        .extracting: "Extrayendo…",
        .run: "Ejecutar",
        .running: "En marcha…",
        .stop: "Detener",
        .preparingWindows: "Preparando Windows…",

        .readyToExtract: "Listo para extraer",
        .readyToRun: "Listo para ejecutar",
        .chooseArchiveFirst: "Elige un comprimido para empezar",
        .chooseProgramFirst: "Elige un programa .exe o .msi",
        .missingExtractorShort: "Falta un extractor",
        .missingWineShort: "Falta Wine",
        .wineBlockedShort: "macOS tiene Wine bloqueado",
        .extractingProgress: "Extrayendo, %@ %%",
        .extractingNoProgress: "Extrayendo…",
        .doneOpenFolder: "Listo. Abrir «%@»",
        .programIsOpen: "El programa está abierto",

        .activity: "Actividad",
        .copyActivity: "Copiar la actividad",
        .clearActivity: "Limpiar la actividad",
        .activityEmpty: "Aquí aparecerá lo que vaya pasando: qué se ejecuta, qué se extrae y qué falla.",
        .allReady: "Todo listo",

        .errorTitle: "Algo no ha salido bien",
        .missingWineTitle: "Falta Wine",
        .missingWineBody: "macOS no abre archivos .exe por su cuenta. Wine es la capa que los traduce. Se instala una vez y la app lo encuentra sola.",
        .howToInstall: "Cómo instalarlo",
        .wineBlockedTitle: "macOS tiene Wine bloqueado",
        .wineBlockedBody: "Wine se descargó de internet y macOS lo cierra nada más abrirlo. Desbloquéalo para poder usarlo: es la misma autorización que darías al abrir la app por primera vez.",
        .unblockWine: "Desbloquear Wine",
        .unblocking: "Desbloqueando…",
        .rosettaTitle: "Falta Rosetta 2",
        .rosettaBody: "Wine es un programa Intel y tu Mac necesita Rosetta 2 para ejecutarlo. Instálalo desde la Terminal con: softwareupdate --install-rosetta",
        .missingExtractorTitle: "Falta un extractor",
        .missingExtractorBody: "macOS no abre archivos .rar por su cuenta. Hacen falta 7zz o unar, dos herramientas libres que se instalan con Homebrew.",
        .install: "Instalar",
        .installingTitle: "Instalando lo que falta",
        .installingBody: "Homebrew está trabajando. Puede tardar unos minutos; mira la actividad de abajo para seguirlo.",

        .windowsCardTitle: "Tu Windows dentro del Mac",
        .windowsCardBody: "La app guarda su propio disco C: en una carpeta aparte, así no toca ninguna otra instalación de Wine que tengas.",
        .wineSettings: "Ajustes de Wine",
        .closeAll: "Cerrar todo",
        .resetWindows: "Restablecer",
        .otherWine: "Otro Wine",
        .wineDisclaimer: "Wine no es Windows: los programas que necesitan controladores, sistemas anti-trampas o gráficos avanzados suelen fallar. Los instaladores y las utilidades sencillas son los que mejor funcionan.",
        .programWillOpen: "Al ejecutarlo se abrirá en su propia ventana, como cualquier programa de Windows.",

        .contentsReading: "Leyendo el contenido…",
        .contentsItems: "%@ elementos dentro",
        .contentsAndMore: "y %@ más",
        .willOpenWith: "Lo abrirá %@",
        .willOpenWithWhy: "7zz no lee varios métodos de RAR antiguos y dejaría los archivos vacíos.",
        .originalUntouched: "El archivo original nunca se borra ni se modifica.",
        .archiveEncrypted: "Pide contraseña",
        .archiveMultipart: "Está partido en varias partes",

        .arch64: "64 bits",
        .arch32: "32 bits",
        .archArm: "ARM64",
        .archUnknown: "arquitectura desconocida",
        .arch32Title: "Puede que no arranque",
        .arch32Warning: "Este programa es de 32 bits y el Wine que tienes solo ejecuta programas de 64 bits. Es probable que no arranque.",

        .wineHelpTitle: "Cómo conseguir Wine",
        .wineHelpBody: "Copia una de estas órdenes y pégala en la Terminal. Cuando termine, vuelve aquí y pulsa «Volver a buscar herramientas».",
        .wineHelpFootnote: "Wine no viene con macOS ni se puede incluir dentro de esta app: es un programa aparte, grande, que se instala una vez. Después la app lo encuentra sola.",
        .copyCommand: "Copiar orden",
        .close: "Cerrar",
        .findWineOnMac: "Buscar Wine en el Mac",
        .wineOptionGptk: "Game Porting Toolkit",
        .wineOptionGptkWhy: "Gratis. La compilación que mantiene la comunidad para Mac con chip Apple.",
        .wineOptionCrossover: "CrossOver",
        .wineOptionCrossoverWhy: "De pago, con 14 días de prueba. Es la más fiable con diferencia.",
        .wineOptionExisting: "Ya tengo uno",
        .wineOptionExistingWhy: "Si ya tienes Wine en el Mac, señálalo a mano con «Otro Wine».",

        .logProgramChosen: "Programa elegido: %@",
        .logArchiveChosen: "Comprimido elegido: %@",
        .logDestination: "Destino: %@",
        .logToolsFound: "Herramientas: %@",
        .logNoTools: "No se encontró ninguna herramienta.",
        .logExtracting: "Extrayendo %@ con %@…",
        .logExtractedTo: "Listo. El contenido está en %@",
        .logOriginalKept: "El archivo original no se ha tocado.",
        .logStopped: "Extracción detenida. Lo ya extraído sigue en la carpeta.",
        .logStopping: "Deteniendo…",
        .logRetryingWith: "%@ no pudo con este archivo. Probando con %@…",
        .logFirstRun: "Primer arranque: creando el entorno de Windows. Puede tardar un par de minutos.",
        .logWindowsReady: "Entorno de Windows listo.",
        .logProgramClosed: "El programa se cerró.",
        .logWineChosen: "Wine elegido a mano: %@",
        .logCommandCopied: "Orden copiada. Pégala en la Terminal.",
        .logActivityCopied: "Actividad copiada al portapapeles.",
        .logExtractorsPresent: "Los extractores ya están instalados.",
        .logInstalling: "Instalando con Homebrew: %@",
        .logInstallTakesTime: "Suele tardar un par de minutos.",
        .logInstallDone: "Instalación terminada.",
        .logWindowsReset: "Entorno de Windows borrado. Se creará de nuevo la próxima vez que ejecutes algo.",
        .logWineUnblocked: "Wine desbloqueado. Ya se pueden ejecutar programas de Windows.",

        .errNotAProgram: "«%@» no es un programa de Windows. Se admiten .exe y .msi.",
        .errNotAnArchive: "«%@» no es un archivo comprimido. Se admiten .rar, .zip, .7z y similares.",
        .errUnknownFile: "No se reconoce «%@». Admite .exe, .msi y comprimidos como .rar o .zip.",
        .errNoWine: "No hay Wine disponible. Instálalo o búscalo a mano.",
        .errNoExtractor: "No hay ningún extractor instalado. Pulsa «Instalar».",
        .errPickProgram: "Elige un programa .exe o .msi válido.",
        .errPickArchive: "Elige un archivo comprimido válido.",
        .errPickDestination: "Elige una carpeta de destino.",
        .errCannotCreateFolder: "No se pudo crear la carpeta «%@»: %@",
        .errWineBlocked: "macOS tiene Wine bloqueado porque lo marcó como descargado de internet. Pulsa «Desbloquear Wine» y vuelve a intentarlo.",
        .errNoRosetta: "Falta Rosetta 2, que Wine necesita en los Mac con chip Apple. Instálalo con: softwareupdate --install-rosetta",
        .errWinePrefixFailed: "Este Wine no consigue crear el entorno de Windows. Suele pasar con las versiones de WineHQ que ya no son compatibles con macOS. Prueba con otro desde «Otro Wine».",
        .errUnblockFailed: "No se pudo desbloquear Wine. Desde la Terminal: xattr -dr com.apple.quarantine \"%@\"",
        .errNotWineExecutable: "Ahí no hay un ejecutable de Wine. Busca el archivo «wine» o una app «Wine…app».",
        .errProgramExit: "El programa terminó con el código %@. Muchos programas de Windows no funcionan bajo Wine: los que necesitan controladores, anti-trampas o gráficos especiales suelen fallar.",
        .errExtractExit2: "Ningún extractor pudo con este comprimido. Si tiene contraseña, escríbela arriba; si está partido en varias partes, déjalas todas en la misma carpeta.",
        .errExtractExit1: "La extracción terminó con avisos. Revisa la actividad: puede que algún archivo se haya saltado.",
        .errExtractExitOther: "El extractor terminó con el código %@. Revisa la actividad para ver el motivo.",
        .errBusy: "Espera a que termine el programa que está en marcha.",
        .errHomebrewMissing: "Homebrew no está instalado. Instálalo desde brew.sh y vuelve a intentarlo.",
        .errInstallFailed: "Homebrew terminó con el código %@. Revisa la actividad para ver el motivo.",

        .statusFinished: "Terminado",
        .statusStopped: "Detenido",
        .statusExtracted: "Extraído",
        .statusFailed: "Terminó con errores",
        .statusCannotStart: "No se pudo iniciar",
        .statusExtracting: "Extrayendo %@",
        .statusRunning: "Ejecutando %@",
        .statusInstalling: "Instalando",
        .statusToolsInstalled: "Extractores instalados",
        .statusWindowsReset: "Windows restablecido",
        .statusWineUnblocked: "Wine desbloqueado",
        .statusPreparing: "Preparando Windows",
        .statusWindowsFailed: "No se pudo preparar Windows"
    ]

    private static let englishTable: [TextKey: String] = [
        .tabPrograms: "Programs",
        .tabArchives: "Archives",
        .toolWine: "Wine",
        .toolExtractor: "Extractor",
        .toolNotInstalled: "not installed",
        .languageMenu: "Language",

        .menuTools: "Tools",
        .menuRefresh: "Look for tools again",
        .menuInstallExtractors: "Install the extractors",
        .menuFindWine: "Find Wine manually…",
        .menuForgetWine: "Forget the chosen Wine",
        .menuUnblockWine: "Unblock Wine",
        .menuResetWindows: "Reset Windows",
        .menuOpenWindowsFolder: "Open the Windows folder",
        .menuOpenProgram: "Open Windows program…",
        .menuOpenArchive: "Open archive…",
        .menuCopyActivity: "Copy the activity",
        .menuClearActivity: "Clear the activity",

        .dropProgramTitle: "Drop a Windows program here",
        .dropProgramSubtitle: "Files ending in .exe and .msi. You can also click to browse.",
        .dropArchiveTitle: "Drop an archive here",
        .dropArchiveSubtitle: "Files ending in .rar, .zip, .7z, .tar, .iso. You can also click to browse.",

        .revealInFinder: "Show in Finder",
        .removeFile: "Remove the file",
        .chooseAnotherProgram: "Choose another program",
        .chooseAnotherArchive: "Choose another archive",

        .saveIn: "Save into",
        .change: "Change",
        .automatic: "Automatic",
        .ownFolder: "Own folder",
        .ownFolderHint: "Named after the archive",
        .password: "Password",
        .passwordHint: "Only if it asks",
        .passwordNone: "None",
        .ifExists: "If it already exists",
        .whenDone: "When finished",
        .whenDoneHint: "Open in Finder",
        .policySkip: "Keep the existing ones",
        .policyRename: "Rename the new ones",
        .policyOverwrite: "Overwrite",
        .policySkipWhy: "If a file is already in the folder, it is left alone.",
        .policyRenameWhy: "Repeated files are saved under a different name.",
        .policyOverwriteWhy: "Repeated files are replaced by the ones in the archive.",

        .extract: "Extract",
        .extracting: "Extracting…",
        .run: "Run",
        .running: "Running…",
        .stop: "Stop",
        .preparingWindows: "Preparing Windows…",

        .readyToExtract: "Ready to extract",
        .readyToRun: "Ready to run",
        .chooseArchiveFirst: "Choose an archive to begin",
        .chooseProgramFirst: "Choose an .exe or .msi program",
        .missingExtractorShort: "No extractor installed",
        .missingWineShort: "Wine is missing",
        .wineBlockedShort: "macOS has Wine blocked",
        .extractingProgress: "Extracting, %@ %%",
        .extractingNoProgress: "Extracting…",
        .doneOpenFolder: "Done. Open “%@”",
        .programIsOpen: "The program is open",

        .activity: "Activity",
        .copyActivity: "Copy the activity",
        .clearActivity: "Clear the activity",
        .activityEmpty: "What happens will show up here: what runs, what gets extracted, and what fails.",
        .allReady: "Ready",

        .errorTitle: "That did not work",
        .missingWineTitle: "Wine is missing",
        .missingWineBody: "macOS cannot open .exe files on its own. Wine is the layer that translates them. You install it once and the app finds it by itself.",
        .howToInstall: "How to install it",
        .wineBlockedTitle: "macOS has Wine blocked",
        .wineBlockedBody: "Wine was downloaded from the internet and macOS closes it the moment it opens. Unblock it to use it: it is the same permission you would give when opening an app for the first time.",
        .unblockWine: "Unblock Wine",
        .unblocking: "Unblocking…",
        .rosettaTitle: "Rosetta 2 is missing",
        .rosettaBody: "Wine is an Intel program and your Mac needs Rosetta 2 to run it. Install it from Terminal with: softwareupdate --install-rosetta",
        .missingExtractorTitle: "No extractor installed",
        .missingExtractorBody: "macOS cannot open .rar files on its own. It needs 7zz or unar, two free tools that install with Homebrew.",
        .install: "Install",
        .installingTitle: "Installing what is missing",
        .installingBody: "Homebrew is working. It can take a few minutes; watch the activity below to follow it.",

        .windowsCardTitle: "Your Windows inside the Mac",
        .windowsCardBody: "The app keeps its own C: drive in a separate folder, so it never touches any other Wine installation you have.",
        .wineSettings: "Wine settings",
        .closeAll: "Close everything",
        .resetWindows: "Reset",
        .otherWine: "Other Wine",
        .wineDisclaimer: "Wine is not Windows: programs that need drivers, anti-cheat systems or advanced graphics usually fail. Installers and simple utilities are the ones that work best.",
        .programWillOpen: "When you run it, it opens in its own window, like any Windows program.",

        .contentsReading: "Reading the contents…",
        .contentsItems: "%@ items inside",
        .contentsAndMore: "and %@ more",
        .willOpenWith: "%@ will open it",
        .willOpenWithWhy: "7zz cannot read several older RAR methods and would leave the files empty.",
        .originalUntouched: "The original file is never deleted or modified.",
        .archiveEncrypted: "Asks for a password",
        .archiveMultipart: "Split across several parts",

        .arch64: "64-bit",
        .arch32: "32-bit",
        .archArm: "ARM64",
        .archUnknown: "unknown architecture",
        .arch32Title: "It may not start",
        .arch32Warning: "This program is 32-bit and the Wine you have only runs 64-bit programs. It will probably not start.",

        .wineHelpTitle: "How to get Wine",
        .wineHelpBody: "Copy one of these commands and paste it into Terminal. When it finishes, come back here and press “Look for tools again”.",
        .wineHelpFootnote: "Wine does not come with macOS and cannot be bundled inside this app: it is a separate, large program that you install once. After that the app finds it by itself.",
        .copyCommand: "Copy command",
        .close: "Close",
        .findWineOnMac: "Find Wine on the Mac",
        .wineOptionGptk: "Game Porting Toolkit",
        .wineOptionGptkWhy: "Free. The build the community maintains for Apple silicon Macs.",
        .wineOptionCrossover: "CrossOver",
        .wineOptionCrossoverWhy: "Paid, with a 14-day trial. By far the most reliable one.",
        .wineOptionExisting: "I already have one",
        .wineOptionExistingWhy: "If Wine is already on your Mac, point at it with “Other Wine”.",

        .logProgramChosen: "Program chosen: %@",
        .logArchiveChosen: "Archive chosen: %@",
        .logDestination: "Destination: %@",
        .logToolsFound: "Tools: %@",
        .logNoTools: "No tools were found.",
        .logExtracting: "Extracting %@ with %@…",
        .logExtractedTo: "Done. The contents are in %@",
        .logOriginalKept: "The original file was not touched.",
        .logStopped: "Extraction stopped. What was already extracted stays in the folder.",
        .logStopping: "Stopping…",
        .logRetryingWith: "%@ could not handle this file. Trying with %@…",
        .logFirstRun: "First run: creating the Windows environment. This can take a couple of minutes.",
        .logWindowsReady: "Windows environment ready.",
        .logProgramClosed: "The program closed.",
        .logWineChosen: "Wine chosen manually: %@",
        .logCommandCopied: "Command copied. Paste it into Terminal.",
        .logActivityCopied: "Activity copied to the clipboard.",
        .logExtractorsPresent: "The extractors are already installed.",
        .logInstalling: "Installing with Homebrew: %@",
        .logInstallTakesTime: "This usually takes a couple of minutes.",
        .logInstallDone: "Installation finished.",
        .logWindowsReset: "Windows environment deleted. It will be created again the next time you run something.",
        .logWineUnblocked: "Wine unblocked. Windows programs can run now.",

        .errNotAProgram: "“%@” is not a Windows program. Only .exe and .msi are accepted.",
        .errNotAnArchive: "“%@” is not an archive. Accepted formats include .rar, .zip and .7z.",
        .errUnknownFile: "“%@” is not recognised. It accepts .exe, .msi and archives such as .rar or .zip.",
        .errNoWine: "No Wine available. Install it or point at it manually.",
        .errNoExtractor: "No extractor is installed. Press “Install”.",
        .errPickProgram: "Choose a valid .exe or .msi program.",
        .errPickArchive: "Choose a valid archive.",
        .errPickDestination: "Choose a destination folder.",
        .errCannotCreateFolder: "Could not create the folder “%@”: %@",
        .errWineBlocked: "macOS has Wine blocked because it was marked as downloaded from the internet. Press “Unblock Wine” and try again.",
        .errNoRosetta: "Rosetta 2 is missing, and Wine needs it on Apple silicon Macs. Install it with: softwareupdate --install-rosetta",
        .errWinePrefixFailed: "This Wine cannot create the Windows environment. It usually happens with WineHQ versions that no longer work on macOS. Try another one from “Other Wine”.",
        .errUnblockFailed: "Wine could not be unblocked. From Terminal: xattr -dr com.apple.quarantine \"%@\"",
        .errNotWineExecutable: "There is no Wine executable there. Look for the “wine” file or a “Wine….app”.",
        .errProgramExit: "The program finished with code %@. Many Windows programs do not work under Wine: the ones needing drivers, anti-cheat or special graphics usually fail.",
        .errExtractExit2: "No extractor could open this archive. If it has a password, type it above; if it is split into parts, keep them all in the same folder.",
        .errExtractExit1: "The extraction finished with warnings. Check the activity: some file may have been skipped.",
        .errExtractExitOther: "The extractor finished with code %@. Check the activity to see why.",
        .errBusy: "Wait until the program that is running finishes.",
        .errHomebrewMissing: "Homebrew is not installed. Install it from brew.sh and try again.",
        .errInstallFailed: "Homebrew finished with code %@. Check the activity to see why.",

        .statusFinished: "Finished",
        .statusStopped: "Stopped",
        .statusExtracted: "Extracted",
        .statusFailed: "Finished with errors",
        .statusCannotStart: "Could not start",
        .statusExtracting: "Extracting %@",
        .statusRunning: "Running %@",
        .statusInstalling: "Installing",
        .statusToolsInstalled: "Extractors installed",
        .statusWindowsReset: "Windows reset",
        .statusWineUnblocked: "Wine unblocked",
        .statusPreparing: "Preparing Windows",
        .statusWindowsFailed: "Could not prepare Windows"
    ]
}
