import Foundation

/// Tabla de texto para un idioma. Se accede por clave, y una prueba comprueba que ningún
/// idioma deje claves fuera.
public struct Strings: Sendable {
    public let language: Language
    private let table: [TextKey: String]

    public subscript(_ key: TextKey) -> String {
        table[key] ?? key.rawValue
    }

    /// Para los textos que llevan `%@`.
    public func callAsFunction(_ key: TextKey, _ arguments: CVarArg...) -> String {
        String(format: self[key], arguments: arguments)
    }

    public static func table(for language: Language) -> Strings {
        Strings(language: language, table: language == .spanish ? spanishTable : englishTable)
    }

    /// Expuesta para que las pruebas comprueben la cobertura de claves.
    public static func rawTable(for language: Language) -> [TextKey: String] {
        language == .spanish ? spanishTable : englishTable
    }

    private static let spanishTable: [TextKey: String] = [
        .tabPrograms: "Programas",
        .tabArchives: "Comprimidos",
        .tabAndroid: "Android",
        .toolWine: "Wine",
        .toolExtractor: "Extractor",
        .toolAndroid: "Android",
        .toolNotInstalled: "sin instalar",
        .languageMenu: "Idioma",

        .menuTools: "Herramientas",
        .menuRefresh: "Volver a buscar herramientas",
        .menuInstallMissing: "Instalar lo que falta",
        .menuFindWine: "Buscar Wine a mano…",
        .menuForgetWine: "Olvidar el Wine elegido",
        .menuUnblockWine: "Desbloquear Wine",
        .menuResetWindows: "Restablecer Windows",
        .menuOpenWindowsFolder: "Abrir la carpeta de Windows",
        .menuOpenProgram: "Abrir programa de Windows…",
        .menuOpenArchive: "Abrir comprimido…",
        .menuOpenApk: "Abrir app de Android…",
        .menuScanDevices: "Buscar aparatos Android",
        .menuCopyActivity: "Copiar la actividad",
        .menuClearActivity: "Limpiar la actividad",

        .dropProgramTitle: "Suelta aquí un programa de Windows",
        .dropProgramSubtitle: "Archivos .exe y .msi. También puedes pulsar para buscarlo.",
        .dropArchiveTitle: "Suelta aquí un archivo comprimido",
        .dropArchiveSubtitle: "Archivos .rar, .zip, .7z, .tar, .iso. También puedes pulsar para buscarlo.",
        .dropApkTitle: "Suelta aquí una app de Android",
        .dropApkSubtitle: "Archivos .apk, .xapk, .apks y .aab. También puedes pulsar para buscarla.",

        .revealInFinder: "Mostrar en el Finder",
        .removeFile: "Quitar el archivo",
        .chooseAnotherProgram: "Elegir otro programa",
        .chooseAnotherArchive: "Elegir otro comprimido",

        .saveIn: "Guardar en",
        .change: "Cambiar",
        .automatic: "Automático",
        .ownFolder: "Carpeta propia",
        .ownFolderHint: "Con el nombre del comprimido",
        .password: "Contraseña",
        .passwordHint: "Solo si la pide",
        .passwordNone: "Ninguna",
        .ifExists: "Si ya existe",
        .whenDone: "Al terminar",
        .whenDoneHint: "Abrir en el Finder",
        .policySkip: "Conservar los existentes",
        .policyRename: "Renombrar los nuevos",
        .policyOverwrite: "Sobrescribir",
        .policySkipWhy: "Si un archivo ya está en la carpeta, se deja como está.",
        .policyRenameWhy: "Los archivos repetidos se guardan con otro nombre.",
        .policyOverwriteWhy: "Los archivos repetidos se reemplazan por los del comprimido.",

        .extract: "Extraer",
        .extracting: "Extrayendo…",
        .run: "Ejecutar",
        .running: "En marcha…",
        .stop: "Detener",
        .preparingWindows: "Preparando Windows…",
        .installingApk: "Instalando…",
        .openApp: "Abrir la app",
        .uninstall: "Desinstalar",
        .uninstalling: "Desinstalando…",

        .readyToExtract: "Listo para extraer",
        .readyToRun: "Listo para ejecutar",
        .chooseArchiveFirst: "Elige un comprimido para empezar",
        .chooseProgramFirst: "Elige un programa .exe o .msi",
        .missingExtractorShort: "Falta un extractor",
        .missingWineShort: "Falta Wine",
        .wineBlockedShort: "macOS tiene Wine bloqueado",
        .extractingProgress: "Extrayendo, %@ %%",
        .extractingNoProgress: "Extrayendo…",
        .doneOpenFolder: "Listo. Abrir «%@»",
        .programIsOpen: "El programa está abierto",

        .activity: "Actividad",
        .copyActivity: "Copiar la actividad",
        .clearActivity: "Limpiar la actividad",
        .activityEmpty: "Aquí aparecerá lo que vaya pasando: qué se ejecuta, qué se extrae y qué falla.",
        .allReady: "Todo listo",

        .errorTitle: "Algo no ha salido bien",
        .missingWineTitle: "Falta Wine",
        .missingWineBody: "macOS no abre archivos .exe por su cuenta. Wine es la capa que los traduce. Se instala una vez y la app lo encuentra sola.",
        .howToInstall: "Cómo instalarlo",
        .wineBlockedTitle: "macOS tiene Wine bloqueado",
        .wineBlockedBody: "Wine se descargó de internet y macOS lo cierra nada más abrirlo. Desbloquéalo para poder usarlo: es la misma autorización que darías al abrir la app por primera vez.",
        .unblockWine: "Desbloquear Wine",
        .unblocking: "Desbloqueando…",
        .rosettaTitle: "Falta Rosetta 2",
        .rosettaBody: "Wine es un programa Intel y tu Mac necesita Rosetta 2 para ejecutarlo. Instálalo desde la Terminal con: softwareupdate --install-rosetta",
        .missingExtractorTitle: "Falta un extractor",
        .missingExtractorBody: "macOS no abre archivos .rar por su cuenta. Hacen falta 7zz o unar, dos herramientas libres que se instalan con Homebrew.",
        .install: "Instalar",
        .installingTitle: "Instalando lo que falta",
        .installingBody: "Homebrew está trabajando. Puede tardar unos minutos; mira la actividad de abajo para seguirlo.",

        .windowsCardTitle: "Tu Windows dentro del Mac",
        .windowsCardBody: "La app guarda su propio disco C: en una carpeta aparte, así no toca ninguna otra instalación de Wine que tengas.",
        .wineSettings: "Ajustes de Wine",
        .closeAll: "Cerrar todo",
        .resetWindows: "Restablecer",
        .otherWine: "Otro Wine",
        .wineDisclaimer: "Wine no es Windows: los programas que necesitan controladores, sistemas anti-trampas o gráficos avanzados suelen fallar. Los instaladores y las utilidades sencillas son los que mejor funcionan.",
        .programWillOpen: "Al ejecutarlo se abrirá en su propia ventana, como cualquier programa de Windows.",

        .contentsReading: "Leyendo el contenido…",
        .contentsItems: "%@ elementos dentro",
        .contentsAndMore: "y %@ más",
        .willOpenWith: "Lo abrirá %@",
        .willOpenWithWhy: "7zz no lee varios métodos de RAR antiguos y dejaría los archivos vacíos.",
        .originalUntouched: "El archivo original nunca se borra ni se modifica.",
        .archiveEncrypted: "Pide contraseña",
        .archiveMultipart: "Está partido en varias partes",

        .arch64: "64 bits",
        .arch32: "32 bits",
        .archArm: "ARM64",
        .archUnknown: "arquitectura desconocida",
        .arch32Title: "Puede que no arranque",
        .arch32Warning: "Este programa es de 32 bits y el Wine que tienes solo ejecuta programas de 64 bits. Es probable que no arranque.",

        .portableTitle: "Este juego está hecho con %@",
        .portableBodyGodot: "En Godot el .exe es solo el motor: el juego entero está en el .pck de al lado, y ese archivo sirve igual en Mac. Lever puede juntarlo con el motor oficial de macOS y dejarte una app nativa, sin Wine y sin Rosetta.",
        .portableMakeApp: "Crear app de Mac",
        .portablePorting: "Creando la app…",
        .portableWhereItGoes: "La app aparecerá en el Escritorio. El juego original no se toca.",
        .portablePartsNeeded: "Este juego usa complementos nativos que el desarrollador no compiló para Mac: %@",
        .portableBuildParts: "Compilar también los complementos que faltan",
        .recipeGozen: "reproduce los vídeos en .mp4",
        .portablePartUnknown: "Lever no sabe compilar este. La app se creará igual, pero lo que dependa de él fallará.",
        .portableUnsupportedGodot: "Por ahora solo se pueden trasladar juegos de Godot 4. Este es de Godot %@.",
        .portableBodyRenpy: "Ren'Py es un intérprete de Python: el guion y los recursos del juego no saben en qué sistema corren. Lo único atado a Windows es el intérprete, y Ren'Py publica el suyo para Mac. Lever los empareja y te deja una app nativa.",
        .portableUnsupportedRenpy: "Esta versión de Ren'Py (%@) es demasiado antigua: sus binarios de Mac son de 32 bits y macOS ya no los ejecuta.",
        .portableRosettaNote: "Esta versión del motor solo tiene binarios de Intel, así que la app irá con Rosetta. Funciona, pero no tan fina como una de Apple silicon.",
        .portableBodyLove: "En LÖVE el .exe es el motor con el juego pegado detrás, y ese juego es Lua y recursos: no sabe en qué sistema corre. LÖVE publica su motor para Mac, así que Lever separa las dos mitades y las vuelve a juntar del lado bueno.",
        .portableUnsupportedLove: "Esta versión de LÖVE (%@) es demasiado antigua: sus binarios de Mac son de 32 bits y macOS ya no los ejecuta.",
        .portableBodyNwjs: "NW.js es Chromium con Node dentro, y el juego que corre encima es HTML y JavaScript: no sabe en qué sistema está. Es lo que usan RPG Maker MV y MZ. NW.js publica su motor para Mac, así que Lever cambia una mitad por la otra.",
        .portableUnsupportedNwjs: "Este juego trae NW.js %@ y Lever no puede trasladarlo.",
        .portableBodyElectron: "Electron es Chromium con Node dentro, y el juego que corre encima es HTML y JavaScript: no sabe en qué sistema está. Electron publica su motor para Mac, así que Lever cambia una mitad por la otra. Si el juego trae complementos nativos, Lever busca la versión de Mac que publique cada uno y te dice cuáles no la tienen.",
        .portableUnsupportedElectron: "Este juego trae Electron %@ y Lever no puede trasladarlo.",
        .portableBodyJava: "Java no compila el juego para ningún sistema: lo deja en bytecode, que es el mismo en todas partes. De Windows solo son el lanzador, que se tira, y los binarios de las librerías nativas, que Lever cambia por los que el propio proyecto publica para Mac. No hace falta tener Java instalado: la app se lleva el suyo dentro.",
        .portableUnsupportedJava: "Este juego pide Java %@, y no hay ninguna versión publicada de Temurin que sepa leer su bytecode.",
        .portableNwjsNewerEngine: "La versión de NW.js que trae este juego ya no dibuja nada en macOS actual: abre la ventana y se queda en negro. Lever monta en su lugar la más antigua que sí funciona. El juego es HTML y JavaScript y no está atado a su motor, pero si depende de algo que el navegador de entonces hacía de otra manera, podría notarse.",
        .portableRuntimeCached: "El motor de esta versión ya está descargado: será rápido.",
        .portableRuntimeDownload: "La primera vez hay que descargar el motor de la versión %@ (unos %@). Queda guardado para los demás juegos de la misma versión.",
        .portStageReading: "Leyendo el juego",
        .portStageDownloading: "Descargando el motor, versión %@",
        .portStageUnpacking: "Sacando el motor de macOS",
        .portStageBuilding: "Compilando %@ (esto tarda; puedes seguir con otra cosa)",
        .portStageAssembling: "Montando la app",
        .portStageSigning: "Firmando la app",
        .logPortableDetected: "Juego de Godot %@ detectado. Puede correr nativo, sin Wine.",
        .logPorted: "Listo. La app está en %@",
        .logPortUnresolved: "Sin parte de macOS: %@. El juego abrirá, pero eso no funcionará.",
        .errPortEngine: "Esa versión del motor no se puede trasladar.",
        .errPortNoSpace: "No hay sitio en el disco. Hacen falta unos %@ libres.",
        .errPortDownload: "No se pudo descargar el motor (código %@). Comprueba la conexión y vuelve a intentarlo.",
        .errPortRuntime: "La descarga del motor no traía los binarios de macOS. Puede que esa versión no los publique.",
        .errPortAssembly: "No se pudo montar la app: %@",
        .statusPorting: "Creando la app de Mac",
        .statusPortDone: "App creada",

        .apkMinAndroid: "Android %@ o más nuevo",
        .apkMinApi: "API %@ o más nueva",
        .apkNoNativeCode: "sin código nativo",
        .apkSplitTitle: "No es una app entera",
        .apkSplitBody: "Este .apk es un trozo de un App Bundle: le falta el código principal y Android lo rechazará. Busca el .apk completo de la app.",
        .apkUnreadableTitle: "No se puede leer",
        .apkUnreadableBody: "Por dentro no tiene la forma de un .apk. Puede estar a medio descargar, o ser otra cosa con el nombre cambiado.",
        .tabEmulation: "Consolas",
        .dropRomTitle: "Suelta aquí el juego de una consola",
        .dropRomSubtitle: "ROMs e imágenes de disco. También puedes pulsar para buscarlo.",
        .menuOpenRom: "Abrir juego de consola…",
        .archBits8: "8 bits",
        .archBits16: "16 bits",
        .archBits32: "32 bits",
        .archBits64: "64 bits",
        .archDualScreen: "dos pantallas y táctil",
        .archHybrid: "generación híbrida",
        .romEvidenceHeader: "reconocido por su cabecera",
        .romEvidenceExtension: "reconocido solo por la extensión",
        .romEvidenceNone: "sin reconocer",
        .romUnknownTitle: "No sé de qué consola es",
        .romUnknownBody: "Ni la cabecera del archivo ni su extensión coinciden con ninguna de las máquinas que sé emular. Si sabes cuál es, elígela a mano.",
        .romNeedsBiosTitle: "Esta consola necesita su BIOS",
        .romNeedsBiosBody: "El núcleo pide %@, que no se puede descargar: sale de una consola de verdad. Ponla en la carpeta de sistema y volverá a intentarlo.",
        .romTouchTitle: "Se maneja tocando la pantalla",
        .romTouchBody: "Es una consola de dos pantallas y lápiz. En el Mac la pantalla táctil es el ratón: se apunta y se hace clic sobre la pantalla de abajo.",
        .retroMissingTitle: "Falta RetroArch",
        .retroMissingBody: "Es lo que ejecuta los núcleos, igual que Wine ejecuta los .exe. Son unos 170 MB.",
        .retroCardTitle: "El motor de emulación",
        .retroCardBody: "Lever reconoce el juego, consigue el núcleo de su consola y lanza RetroArch con una configuración propia. La tuya de siempre no se toca.",
        .retroCoreSection: "Núcleo",
        .retroCoreCached: "ya descargado",
        .retroCoreToDownload: "se descargará",
        .retroArchNote: "El núcleo tiene que ser de la misma arquitectura que tu RetroArch (%@), no la del Mac.",
        .controlsSection: "Controles",
        .controlsProfile: "Perfil",
        .controlsEdit: "Cambiar los controles…",
        .controlsScopeGlobal: "para todo",
        .controlsScopePlatform: "solo para esta consola",
        .controlsScopeGame: "solo para este juego",
        .controlsSaveHere: "Guardar",
        .controlsReset: "Volver a lo de fábrica",
        .controlsPressPrompt: "Pulsa la tecla o el botón que quieres para %@",
        .controlsUnassigned: "sin asignar",
        .controlsListening: "Escuchando…",
        .controlsGamepads: "Mandos conectados",
        .controlsNoGamepad: "Ninguno. Enchufa uno por USB o empareja uno por Bluetooth y aparecerá aquí.",
        .controlsKeyboardTab: "Teclado",
        .controlsGamepadTab: "Mando",
        .controlsButton: "botón %@",
        .controlsAxis: "eje %@",
        .controlsHat: "cruceta %@",
        .controlsGamepadHint: "El mando se asigna con el mando: pulsa una casilla y luego el botón "
            + "que quieras. La tecla que tenga puesta se queda como está.",
        .playRom: "Jugar",
        .playingRom: "Jugando",
        .statusGettingCore: "Descargando el núcleo de %@…",
        .statusLaunchingRetro: "Abriendo el juego…",
        .errNoRetroArch: "No encuentro RetroArch. Instálalo y vuelve a intentarlo.",
        .errNoCore: "No se pudo conseguir el núcleo de esta consola.",
        .errUnknownRom: "«%@» no parece el juego de ninguna consola que sepa emular.",
        .errPickRom: "Elige antes el juego que quieres abrir.",
        .emulationDisclaimer: "Lever no trae juegos ni los busca: pon los tuyos. El archivo original nunca se toca, y las partidas guardadas van a una carpeta de Lever, aparte de las de tu RetroArch.",
        .bundleKindXapk: "Este archivo es un .xapk: la app viene partida en varios trozos y Lever elegirá los que le tocan a tu aparato.",
        .bundleKindApks: "Este archivo es un .apks, la salida de bundletool. Dentro hay una tabla que dice qué trozo es para qué aparato, y eso lo lee bundletool.",
        .bundleKindAab: "Este archivo es un App Bundle: no es una app, es lo que el desarrollador sube a Google Play. Hay que generar los .apk de tu aparato a partir de él.",
        .bundleParts: "%@ trozos dentro",
        .bundleExpansions: "%@ de datos aparte",
        .bundleModules: "Trae módulos que Play entrega por su cuenta (%@). Se instalan todos: aquí no hay quien los descargue luego.",
        .bundleUnreadableTitle: "No se pudo abrir el paquete",
        .bundleUnreadableBody: "Por dentro no hay ningún .apk. Puede estar a medio descargar, o ser otra cosa con el nombre cambiado.",
        .bundleToolsTitle: "Hace falta descargar algo",
        .bundleToolsBody: "Para este formato: %@. Se descarga una vez y sirve para todos.",
        .apkUnsignedTitle: "Este .apk viene sin firmar",
        .apkUnsignedBody: "Android no instala una app sin firma. Lever la firmará con una clave suya antes de instalarla; ojo, entonces ya no podrá actualizarse con una versión firmada por su autor.",
        .toolJava: "Java",
        .toolBundletool: "bundletool",
        .toolApkSigner: "el firmador de Android",
        .statusUnpackingBundle: "Sacando los trozos que le tocan a tu aparato…",
        .statusSigningApk: "Firmando el .apk…",
        .statusBuildingApks: "Generando los .apk de tu aparato…",
        .statusInstallingParts: "Instalando %@ trozos como una sola app…",
        .statusPushingExpansion: "Copiando %@ al aparato (%@ de %@)…",
        .statusGettingAndroidTool: "Descargando %@ (%@ MB)…",
        .logApkSigned: "Firmado con la clave de Lever",
        .logPartsInstalled: "Instalados %@ trozos como una sola app",
        .logExpansionsPushed: "Copiados %@ archivos de datos al aparato",
        .errAndroidToolMissing: "Falta %@ y no se ha podido conseguir. Sin eso, este formato no se puede instalar.",
        .errBundleUnreadable: "Dentro del paquete no hay ningún .apk que instalar.",

        .deviceSection: "Dónde instalarla",
        .deviceScanning: "Buscando aparatos…",
        .deviceRefresh: "Buscar otra vez",
        .deviceNoneTitle: "No hay ningún aparato",
        .deviceNoneBody: "Enchufa un móvil Android con la depuración por USB activada, o arranca un emulador de los de abajo.",
        .deviceUnauthorized: "acepta la depuración en su pantalla",
        .deviceOffline: "no responde",
        .deviceEmulator: "emulador",
        .devicePhone: "móvil",
        .deviceAndroidVersion: "Android %@",
        .emulatorSection: "Emuladores",
        .emulatorStart: "Arrancar",
        .emulatorStarting: "Arrancando…",
        .emulatorNone: "No hay ningún emulador creado. Se crean con el SDK de Android.",
        .emulatorHint: "Tarda uno o dos minutos en aparecer arriba, en la lista de aparatos.",

        .abiMismatchTitle: "No va a instalarse",
        .abiMismatchBody: "La app trae código para %@ y este aparato ejecuta %@. Android la rechazará.",
        .sdkTooOldTitle: "El aparato es demasiado antiguo",
        .sdkTooOldBody: "La app pide Android %@ y el aparato tiene Android %@.",
        .missingAdbTitle: "Falta adb",
        .missingAdbBody: "macOS no puede hablar con un aparato Android por su cuenta. adb es el puente: ocupa unos megas y se instala una vez.",
        .androidCardTitle: "El puente con Android",
        .androidCardBody: "adb habla con el móvil por el cable o con el emulador. Esta app no toca nada más del aparato: solo instala, abre y desinstala lo que le pidas.",
        .androidDisclaimer: "Instalar fuera de Google Play se salta sus comprobaciones: pon solo archivos .apk de origen conocido. El paquete se instala tal cual, sin modificarlo.",
        .chooseApkFirst: "Elige una app .apk",
        .readyToInstall: "Listo para instalar",
        .missingAdbShort: "Falta adb",
        .noDeviceShort: "No hay ningún aparato conectado",
        .apkInstalledOn: "Instalada en %@",

        .orientationSection: "Postura de la pantalla",
        .orientationAuto: "Automática",
        .orientationPortrait: "Vertical",
        .orientationLandscape: "Horizontal",
        .orientationFree: "no la fija",
        .orientationDeclared: "El .apk pide %@.",
        .orientationRuntimeWarning: "Su manifiesto no fija ninguna. Muchos juegos la deciden al arrancar, desde su propio código: si sale girado, usa el conmutador.",

        .emulatorSetUp: "Montar el emulador",
        .emulatorSettingUp: "Montando el emulador…",
        .emulatorSetUpTitle: "Falta el emulador de Android",
        .emulatorSetUpBody: "Para abrir un .apk en el Mac hace falta un Android dentro. La app puede montarlo sola: descarga el SDK, la imagen del sistema para tu chip y crea el emulador.",
        .emulatorSetUpSize: "Ocupa unos 6 GB y tarda un rato largo; hacen falta 8 libres. Ahora mismo tienes %@.",
        .emulatorNoSpace: "No queda sitio suficiente en el disco. El emulador necesita unos 6 GB libres y hay %@.",
        .emulatorReady: "Emulador listo. Ya puedes ejecutar un .apk.",
        .runApk: "Ejecutar",
        .runningApk: "Ejecutando…",
        .openAgain: "Abrir otra vez",

        .logRotated: "Pantalla puesta en %@.",
        .logEmulatorReady: "El emulador ya ha arrancado.",
        .statusApkRunning: "Abriendo la app",
        .errEmulatorTimeout: "El emulador tardó demasiado en arrancar. Míralo en su ventana: puede estar pidiendo algo, o le falta memoria.",
        .errEmulatorSetUpFailed: "No se pudo montar el emulador entero. Revisa la actividad; el guion se puede volver a lanzar sin repetir lo ya hecho.",
        .errEmulatorScriptMissing: "Falta el guion que monta el emulador. Reinstala la app con: bash scripts/install.sh",

        .recentsTitle: "Abiertos hace poco",
        .recentsClear: "Vaciar la lista",
        .recentsReopen: "Volver a abrirlo",
        .recentsRename: "Cambiar el nombre",
        .recentsRenameHint: "Se conserva la extensión",
        .recentsMove: "Mover a otra carpeta…",
        .recentsForget: "Quitar de la lista",
        .recentsMissing: "ya no está donde estaba",
        .errRenameEmpty: "Escribe un nombre.",
        .errNameTaken: "Ya hay un archivo llamado «%@» en esa carpeta. El tuyo no se ha tocado.",
        .errRenameFailed: "No se pudo: %@",
        .errRecentMissing: "«%@» ya no está donde estaba. Lo habrán movido o borrado desde fuera.",
        .logRenamed: "Ahora se llama %@",
        .logMoved: "Movido a %@",

        .androidHelpTitle: "Cómo instalar una app de Android",
        .androidHelpBody: "Un .apk no se ejecuta dentro del Mac como un .exe: se instala en un aparato Android. Hay dos maneras de tener uno.",
        .androidHelpFootnote: "El emulador y el SDK ocupan varios gigas y necesitan Java. Si tienes un móvil Android a mano, enchufarlo es mucho más rápido.",
        .androidOptionPhone: "Un móvil enchufado",
        .androidOptionPhoneWhy: "Lo más rápido. En el móvil: Opciones de desarrollador → Depuración por USB. Enchúfalo y acepta el aviso. Solo hace falta adb.",
        .androidOptionEmulator: "Un emulador",
        .androidOptionEmulatorWhy: "Sin móvil. Instala las herramientas de línea de órdenes, baja una imagen de sistema y crea el emulador.",
        .androidOptionStudio: "Android Studio",
        .androidOptionStudioWhy: "Si vas a programar para Android de todos modos: trae el SDK, el emulador y el gestor de aparatos en un solo paquete.",

        .wineHelpTitle: "Cómo conseguir Wine",
        .wineHelpBody: "Copia una de estas órdenes y pégala en la Terminal. Cuando termine, vuelve aquí y pulsa «Volver a buscar herramientas».",
        .wineHelpFootnote: "Wine no viene con macOS ni se puede incluir dentro de esta app: es un programa aparte, grande, que se instala una vez. Después la app lo encuentra sola.",
        .copyCommand: "Copiar orden",
        .close: "Cerrar",
        .findWineOnMac: "Buscar Wine en el Mac",
        .wineOptionGptk: "Game Porting Toolkit",
        .wineOptionGptkWhy: "Gratis. La compilación que mantiene la comunidad para Mac con chip Apple.",
        .wineOptionCrossover: "CrossOver",
        .wineOptionCrossoverWhy: "De pago, con 14 días de prueba. Es la más fiable con diferencia.",
        .wineOptionExisting: "Ya tengo uno",
        .wineOptionExistingWhy: "Si ya tienes Wine en el Mac, señálalo a mano con «Otro Wine».",

        .logProgramChosen: "Programa elegido: %@",
        .logArchiveChosen: "Comprimido elegido: %@",
        .logDestination: "Destino: %@",
        .logToolsFound: "Herramientas: %@",
        .logNoTools: "No se encontró ninguna herramienta.",
        .logExtracting: "Extrayendo %@ con %@…",
        .logExtractedTo: "Listo. El contenido está en %@",
        .logOriginalKept: "El archivo original no se ha tocado.",
        .logStopped: "Extracción detenida. Lo ya extraído sigue en la carpeta.",
        .logStopping: "Deteniendo…",
        .logRetryingWith: "%@ no pudo con este archivo. Probando con %@…",
        .logFirstRun: "Primer arranque: creando el entorno de Windows. Puede tardar un par de minutos.",
        .logWindowsReady: "Entorno de Windows listo.",
        .logProgramClosed: "El programa se cerró.",
        .logWineChosen: "Wine elegido a mano: %@",
        .logCommandCopied: "Orden copiada. Pégala en la Terminal.",
        .logActivityCopied: "Actividad copiada al portapapeles.",
        .logExtractorsPresent: "Los extractores ya están instalados.",
        .logInstalling: "Instalando con Homebrew: %@",
        .logInstallTakesTime: "Suele tardar un par de minutos.",
        .logInstallDone: "Instalación terminada.",
        .logWindowsReset: "Entorno de Windows borrado. Se creará de nuevo la próxima vez que ejecutes algo.",
        .logWineUnblocked: "Wine desbloqueado. Ya se pueden ejecutar programas de Windows.",
        .logApkChosen: "App elegida: %@",
        .logDevicesFound: "Aparatos: %@",
        .logNoDevices: "No hay ningún aparato conectado.",
        .logInstallingApk: "Instalando %@ en %@…",
        .logApkInstalled: "Instalada. Ya está en el aparato.",
        .logApkLaunched: "Abriendo la app en el aparato…",
        .logApkUninstalled: "Desinstalada del aparato.",
        .logEmulatorStarting: "Arrancando el emulador «%@». Tarda un par de minutos.",

        .errNotAProgram: "«%@» no es un programa de Windows. Se admiten .exe y .msi.",
        .errNotAnArchive: "«%@» no es un archivo comprimido. Se admiten .rar, .zip, .7z y similares.",
        .errUnknownFile: "No se reconoce «%@». Admite .exe, .msi y comprimidos como .rar o .zip.",
        .errNoWine: "No hay Wine disponible. Instálalo o búscalo a mano.",
        .errNoExtractor: "No hay ningún extractor instalado. Pulsa «Instalar».",
        .errPickProgram: "Elige un programa .exe o .msi válido.",
        .errPickArchive: "Elige un archivo comprimido válido.",
        .errPickDestination: "Elige una carpeta de destino.",
        .errCannotCreateFolder: "No se pudo crear la carpeta «%@»: %@",
        .errWineBlocked: "macOS tiene Wine bloqueado porque lo marcó como descargado de internet. Pulsa «Desbloquear Wine» y vuelve a intentarlo.",
        .errNoRosetta: "Falta Rosetta 2, que Wine necesita en los Mac con chip Apple. Instálalo con: softwareupdate --install-rosetta",
        .errWinePrefixFailed: "Este Wine no consigue crear el entorno de Windows. Suele pasar con las versiones de WineHQ que ya no son compatibles con macOS. Prueba con otro desde «Otro Wine».",
        .errUnblockFailed: "No se pudo desbloquear Wine. Desde la Terminal: xattr -dr com.apple.quarantine \"%@\"",
        .errNotWineExecutable: "Ahí no hay un ejecutable de Wine. Busca el archivo «wine» o una app «Wine…app».",
        .errProgramExit: "El programa terminó con el código %@. Muchos programas de Windows no funcionan bajo Wine: los que necesitan controladores, anti-trampas o gráficos especiales suelen fallar.",
        .errExtractExit2: "Ningún extractor pudo con este comprimido. Si tiene contraseña, escríbela arriba; si está partido en varias partes, déjalas todas en la misma carpeta.",
        .errExtractExit1: "La extracción terminó con avisos. Revisa la actividad: puede que algún archivo se haya saltado.",
        .errExtractExitOther: "El extractor terminó con el código %@. Revisa la actividad para ver el motivo.",
        .errBusy: "Espera a que termine el programa que está en marcha.",
        .errHomebrewMissing: "Homebrew no está instalado. Instálalo desde brew.sh y vuelve a intentarlo.",
        .errInstallFailed: "Homebrew terminó con el código %@. Revisa la actividad para ver el motivo.",
        .errNotAnApk: "«%@» no es una app de Android. Se admiten .apk, .xapk, .apks y .aab.",
        .errNoAdb: "No hay adb. Instálalo para poder hablar con el aparato.",
        .errNoDevice: "No hay ningún aparato donde instalarla. Enchufa un móvil o arranca un emulador.",
        .errPickApk: "Elige un archivo .apk válido.",
        .errDeviceUnauthorized: "El móvil está enchufado pero no ha autorizado a este Mac. Desbloquéalo y acepta el aviso de depuración por USB.",
        .errInstallNoAbis: "Android rechazó la app: trae código para un procesador distinto del que tiene el aparato.",
        .errInstallOldSdk: "Android rechazó la app: pide una versión de Android más nueva que la del aparato.",
        .errInstallSignature: "Ya hay otra versión de esta app, firmada por otra persona. Desinstala la que está antes de poner esta.",
        .errInstallDowngrade: "El aparato tiene una versión más nueva de esta app. Android no deja bajar de versión sin desinstalar la actual.",
        .errInstallNoSpace: "No queda sitio en el aparato.",
        .errInstallNotSigned: "El .apk no está firmado. Android no instala paquetes sin firma.",
        .errInstallBlocked: "El aparato bloqueó la instalación. Muchos móviles piden activar «Instalar apps por USB» en Opciones de desarrollador, o confirmarlo en pantalla.",
        .errInstallOther: "Android rechazó la app: %@",
        .errNoLauncher: "Se instaló, pero esta app no tiene pantalla propia que abrir. Es lo normal en servicios y complementos.",

        .statusFinished: "Terminado",
        .statusStopped: "Detenido",
        .statusExtracted: "Extraído",
        .statusFailed: "Terminó con errores",
        .statusCannotStart: "No se pudo iniciar",
        .statusExtracting: "Extrayendo %@",
        .statusRunning: "Ejecutando %@",
        .statusInstalling: "Instalando",
        .statusToolsInstalled: "Extractores instalados",
        .statusWindowsReset: "Windows restablecido",
        .statusWineUnblocked: "Wine desbloqueado",
        .statusPreparing: "Preparando Windows",
        .statusWindowsFailed: "No se pudo preparar Windows",
        .statusInstallingApk: "Instalando %@",
        .statusApkInstalled: "Instalada",
        .statusApkUninstalled: "Desinstalada",
        .statusScanning: "Buscando aparatos",
        .statusEmulatorStarting: "Arrancando el emulador"
    ]

    private static let englishTable: [TextKey: String] = [
        .tabPrograms: "Programs",
        .tabArchives: "Archives",
        .tabAndroid: "Android",
        .toolWine: "Wine",
        .toolExtractor: "Extractor",
        .toolAndroid: "Android",
        .toolNotInstalled: "not installed",
        .languageMenu: "Language",

        .menuTools: "Tools",
        .menuRefresh: "Look for tools again",
        .menuInstallMissing: "Install what is missing",
        .menuFindWine: "Find Wine manually…",
        .menuForgetWine: "Forget the chosen Wine",
        .menuUnblockWine: "Unblock Wine",
        .menuResetWindows: "Reset Windows",
        .menuOpenWindowsFolder: "Open the Windows folder",
        .menuOpenProgram: "Open Windows program…",
        .menuOpenArchive: "Open archive…",
        .menuOpenApk: "Open Android app…",
        .menuScanDevices: "Look for Android devices",
        .menuCopyActivity: "Copy the activity",
        .menuClearActivity: "Clear the activity",

        .dropProgramTitle: "Drop a Windows program here",
        .dropProgramSubtitle: "Files ending in .exe and .msi. You can also click to browse.",
        .dropArchiveTitle: "Drop an archive here",
        .dropArchiveSubtitle: "Files ending in .rar, .zip, .7z, .tar, .iso. You can also click to browse.",
        .dropApkTitle: "Drop an Android app here",
        .dropApkSubtitle: "Files ending in .apk, .xapk, .apks and .aab. You can also click to browse.",

        .revealInFinder: "Show in Finder",
        .removeFile: "Remove the file",
        .chooseAnotherProgram: "Choose another program",
        .chooseAnotherArchive: "Choose another archive",

        .saveIn: "Save into",
        .change: "Change",
        .automatic: "Automatic",
        .ownFolder: "Own folder",
        .ownFolderHint: "Named after the archive",
        .password: "Password",
        .passwordHint: "Only if it asks",
        .passwordNone: "None",
        .ifExists: "If it already exists",
        .whenDone: "When finished",
        .whenDoneHint: "Open in Finder",
        .policySkip: "Keep the existing ones",
        .policyRename: "Rename the new ones",
        .policyOverwrite: "Overwrite",
        .policySkipWhy: "If a file is already in the folder, it is left alone.",
        .policyRenameWhy: "Repeated files are saved under a different name.",
        .policyOverwriteWhy: "Repeated files are replaced by the ones in the archive.",

        .extract: "Extract",
        .extracting: "Extracting…",
        .run: "Run",
        .running: "Running…",
        .stop: "Stop",
        .preparingWindows: "Preparing Windows…",
        .installingApk: "Installing…",
        .openApp: "Open the app",
        .uninstall: "Uninstall",
        .uninstalling: "Uninstalling…",

        .readyToExtract: "Ready to extract",
        .readyToRun: "Ready to run",
        .chooseArchiveFirst: "Choose an archive to begin",
        .chooseProgramFirst: "Choose an .exe or .msi program",
        .missingExtractorShort: "No extractor installed",
        .missingWineShort: "Wine is missing",
        .wineBlockedShort: "macOS has Wine blocked",
        .extractingProgress: "Extracting, %@ %%",
        .extractingNoProgress: "Extracting…",
        .doneOpenFolder: "Done. Open “%@”",
        .programIsOpen: "The program is open",

        .activity: "Activity",
        .copyActivity: "Copy the activity",
        .clearActivity: "Clear the activity",
        .activityEmpty: "What happens will show up here: what runs, what gets extracted, and what fails.",
        .allReady: "Ready",

        .errorTitle: "That did not work",
        .missingWineTitle: "Wine is missing",
        .missingWineBody: "macOS cannot open .exe files on its own. Wine is the layer that translates them. You install it once and the app finds it by itself.",
        .howToInstall: "How to install it",
        .wineBlockedTitle: "macOS has Wine blocked",
        .wineBlockedBody: "Wine was downloaded from the internet and macOS closes it the moment it opens. Unblock it to use it: it is the same permission you would give when opening an app for the first time.",
        .unblockWine: "Unblock Wine",
        .unblocking: "Unblocking…",
        .rosettaTitle: "Rosetta 2 is missing",
        .rosettaBody: "Wine is an Intel program and your Mac needs Rosetta 2 to run it. Install it from Terminal with: softwareupdate --install-rosetta",
        .missingExtractorTitle: "No extractor installed",
        .missingExtractorBody: "macOS cannot open .rar files on its own. It needs 7zz or unar, two free tools that install with Homebrew.",
        .install: "Install",
        .installingTitle: "Installing what is missing",
        .installingBody: "Homebrew is working. It can take a few minutes; watch the activity below to follow it.",

        .windowsCardTitle: "Your Windows inside the Mac",
        .windowsCardBody: "The app keeps its own C: drive in a separate folder, so it never touches any other Wine installation you have.",
        .wineSettings: "Wine settings",
        .closeAll: "Close everything",
        .resetWindows: "Reset",
        .otherWine: "Other Wine",
        .wineDisclaimer: "Wine is not Windows: programs that need drivers, anti-cheat systems or advanced graphics usually fail. Installers and simple utilities are the ones that work best.",
        .programWillOpen: "When you run it, it opens in its own window, like any Windows program.",

        .contentsReading: "Reading the contents…",
        .contentsItems: "%@ items inside",
        .contentsAndMore: "and %@ more",
        .willOpenWith: "%@ will open it",
        .willOpenWithWhy: "7zz cannot read several older RAR methods and would leave the files empty.",
        .originalUntouched: "The original file is never deleted or modified.",
        .archiveEncrypted: "Asks for a password",
        .archiveMultipart: "Split across several parts",

        .arch64: "64-bit",
        .arch32: "32-bit",
        .archArm: "ARM64",
        .archUnknown: "unknown architecture",
        .arch32Title: "It may not start",
        .arch32Warning: "This program is 32-bit and the Wine you have only runs 64-bit programs. It will probably not start.",

        .portableTitle: "This game is made with %@",
        .portableBodyGodot: "In Godot the .exe is only the engine: the whole game lives in the .pck next to it, and that file works just as well on a Mac. Lever can pair it with the official macOS engine and hand you a native app, with no Wine and no Rosetta.",
        .portableMakeApp: "Create Mac app",
        .portablePorting: "Creating the app…",
        .portableWhereItGoes: "The app will appear on the Desktop. The original game is left untouched.",
        .portablePartsNeeded: "This game uses native add-ons the developer did not build for Mac: %@",
        .portableBuildParts: "Also compile the missing add-ons",
        .recipeGozen: "plays the .mp4 videos",
        .portablePartUnknown: "Lever does not know how to build this one. The app will still be created, but whatever depends on it will fail.",
        .portableUnsupportedGodot: "For now only Godot 4 games can be converted. This one is Godot %@.",
        .portableBodyRenpy: "Ren'Py is a Python interpreter: the game's script and assets have no idea which system they run on. The only Windows-specific part is the interpreter, and Ren'Py publishes one for Mac. Lever pairs them and hands you a native app.",
        .portableUnsupportedRenpy: "This Ren'Py version (%@) is too old: its Mac binaries are 32-bit and macOS no longer runs them.",
        .portableRosettaNote: "This engine version only ships Intel binaries, so the app will run through Rosetta. It works, but not as smoothly as an Apple silicon one.",
        .portableBodyLove: "In LÖVE the .exe is the engine with the game stuck to the end of it, and that game is Lua and assets: it has no idea which system it runs on. LÖVE publishes its engine for Mac, so Lever splits the two halves apart and joins them back on the right side.",
        .portableUnsupportedLove: "This LÖVE version (%@) is too old: its Mac binaries are 32-bit and macOS no longer runs them.",
        .portableBodyNwjs: "NW.js is Chromium with Node inside it, and the game running on top is HTML and JavaScript: it has no idea which system it is on. RPG Maker MV and MZ use it. NW.js publishes its engine for Mac, so Lever swaps one half for the other.",
        .portableUnsupportedNwjs: "This game ships NW.js %@ and Lever cannot port it.",
        .portableBodyElectron: "Electron is Chromium with Node inside it, and the game running on top is HTML and JavaScript: it has no idea which system it is on. Electron publishes its engine for Mac, so Lever swaps one half for the other. If the game ships native add-ons, Lever looks for the Mac build each one publishes and tells you which ones have none.",
        .portableUnsupportedElectron: "This game ships Electron %@ and Lever cannot port it.",
        .portableBodyJava: "Java does not compile the game for any particular system: it leaves it as bytecode, which is the same everywhere. The only Windows parts are the launcher, which gets dropped, and the native library binaries, which Lever swaps for the ones each project publishes for Mac. You do not need Java installed: the app carries its own.",
        .portableUnsupportedJava: "This game asks for Java %@, and no published Temurin version can read its bytecode.",
        .portableNwjsNewerEngine: "The NW.js version this game ships no longer draws anything on current macOS: it opens a window and stays black. Lever mounts the oldest version that does work instead. The game is HTML and JavaScript and is not tied to its engine, but if it leans on something the browser of that era did differently, it may show.",
        .portableRuntimeCached: "The engine for this version is already downloaded: this will be quick.",
        .portableRuntimeDownload: "The first time, the engine for version %@ has to be downloaded (about %@). It is kept for other games on the same version.",
        .portStageReading: "Reading the game",
        .portStageDownloading: "Downloading the engine, version %@",
        .portStageUnpacking: "Unpacking the macOS engine",
        .portStageBuilding: "Building %@ (this takes a while; feel free to do something else)",
        .portStageAssembling: "Assembling the app",
        .portStageSigning: "Signing the app",
        .logPortableDetected: "Godot %@ game detected. It can run natively, without Wine.",
        .logPorted: "Done. The app is in %@",
        .logPortUnresolved: "No macOS part for: %@. The game will open, but that will not work.",
        .errPortEngine: "That engine version cannot be converted.",
        .errPortNoSpace: "There is no room on the disk. About %@ free are needed.",
        .errPortDownload: "The engine could not be downloaded (code %@). Check the connection and try again.",
        .errPortRuntime: "The engine download had no macOS binaries inside. That version may not publish them.",
        .errPortAssembly: "The app could not be assembled: %@",
        .statusPorting: "Creating the Mac app",
        .statusPortDone: "App created",

        .apkMinAndroid: "Android %@ or newer",
        .apkMinApi: "API %@ or newer",
        .apkNoNativeCode: "no native code",
        .apkSplitTitle: "Not a whole app",
        .apkSplitBody: "This .apk is one piece of an App Bundle: the main code is missing and Android will reject it. Look for the app’s complete .apk.",
        .apkUnreadableTitle: "It cannot be read",
        .apkUnreadableBody: "Inside, it does not have the shape of an .apk. It may be half-downloaded, or something else with its name changed.",
        .tabEmulation: "Consoles",
        .dropRomTitle: "Drop a console game here",
        .dropRomSubtitle: "ROMs and disc images. You can also click to browse.",
        .menuOpenRom: "Open console game…",
        .archBits8: "8-bit",
        .archBits16: "16-bit",
        .archBits32: "32-bit",
        .archBits64: "64-bit",
        .archDualScreen: "dual screen and touch",
        .archHybrid: "hybrid generation",
        .romEvidenceHeader: "recognised by its header",
        .romEvidenceExtension: "recognised by its extension alone",
        .romEvidenceNone: "not recognised",
        .romUnknownTitle: "I cannot tell which console this is for",
        .romUnknownBody: "Neither the file header nor its extension matches any machine I know how to emulate. If you know which one it is, pick it by hand.",
        .romNeedsBiosTitle: "This console needs its BIOS",
        .romNeedsBiosBody: "The core asks for %@, which cannot be downloaded: it comes from a real console. Put it in the system folder and it will try again.",
        .romTouchTitle: "It is played by touching the screen",
        .romTouchBody: "This is a dual-screen console with a stylus. On the Mac the touch screen is the mouse: you point and click on the bottom screen.",
        .retroMissingTitle: "RetroArch is missing",
        .retroMissingBody: "It is what runs the cores, the way Wine runs .exe files. About 170 MB.",
        .retroCardTitle: "The emulation engine",
        .retroCardBody: "Lever recognises the game, gets its console's core and launches RetroArch with a configuration of its own. Yours is left alone.",
        .retroCoreSection: "Core",
        .retroCoreCached: "already downloaded",
        .retroCoreToDownload: "will be downloaded",
        .retroArchNote: "The core has to match your RetroArch's architecture (%@), not the Mac's.",
        .controlsSection: "Controls",
        .controlsProfile: "Profile",
        .controlsEdit: "Change the controls…",
        .controlsScopeGlobal: "for everything",
        .controlsScopePlatform: "for this console only",
        .controlsScopeGame: "for this game only",
        .controlsSaveHere: "Save",
        .controlsReset: "Back to the defaults",
        .controlsPressPrompt: "Press the key or button you want for %@",
        .controlsUnassigned: "unassigned",
        .controlsListening: "Listening…",
        .controlsGamepads: "Connected controllers",
        .controlsNoGamepad: "None. Plug one in over USB or pair one over Bluetooth and it will show up here.",
        .controlsKeyboardTab: "Keyboard",
        .controlsGamepadTab: "Controller",
        .controlsButton: "button %@",
        .controlsAxis: "axis %@",
        .controlsHat: "d-pad %@",
        .controlsGamepadHint: "The controller is mapped with the controller: click a slot and then "
            + "press the button you want. The key it already has stays put.",
        .playRom: "Play",
        .playingRom: "Playing",
        .statusGettingCore: "Downloading the %@ core…",
        .statusLaunchingRetro: "Opening the game…",
        .errNoRetroArch: "I cannot find RetroArch. Install it and try again.",
        .errNoCore: "This console's core could not be obtained.",
        .errUnknownRom: "“%@” does not look like a game for any console I can emulate.",
        .errPickRom: "Pick the game you want to open first.",
        .emulationDisclaimer: "Lever ships no games and looks for none: bring your own. The original file is never touched, and saves go to a Lever folder, apart from your RetroArch's.",
        .bundleKindXapk: "This file is an .xapk: the app comes split into several pieces, and Lever will pick the ones your device needs.",
        .bundleKindApks: "This file is an .apks, the output of bundletool. Inside there is a table saying which piece goes to which device, and bundletool is what reads it.",
        .bundleKindAab: "This file is an App Bundle: not an app, but what the developer uploads to Google Play. The .apk files for your device have to be generated from it.",
        .bundleParts: "%@ pieces inside",
        .bundleExpansions: "%@ of separate data",
        .bundleModules: "It carries modules that Play delivers on its own (%@). All of them are installed: there is nobody here to download them later.",
        .bundleUnreadableTitle: "The bundle could not be opened",
        .bundleUnreadableBody: "There is no .apk inside. It may be half-downloaded, or something else with its name changed.",
        .bundleToolsTitle: "Something needs downloading",
        .bundleToolsBody: "For this format: %@. It is downloaded once and serves every app.",
        .apkUnsignedTitle: "This .apk comes unsigned",
        .apkUnsignedBody: "Android will not install an unsigned app. Lever will sign it with a key of its own first; note that it will then no longer update over a version signed by its author.",
        .toolJava: "Java",
        .toolBundletool: "bundletool",
        .toolApkSigner: "the Android signer",
        .statusUnpackingBundle: "Taking out the pieces your device needs…",
        .statusSigningApk: "Signing the .apk…",
        .statusBuildingApks: "Generating the .apk files for your device…",
        .statusInstallingParts: "Installing %@ pieces as a single app…",
        .statusPushingExpansion: "Copying %@ to the device (%@ of %@)…",
        .statusGettingAndroidTool: "Downloading %@ (%@ MB)…",
        .logApkSigned: "Signed with Lever's key",
        .logPartsInstalled: "Installed %@ pieces as a single app",
        .logExpansionsPushed: "Copied %@ data files to the device",
        .errAndroidToolMissing: "%@ is missing and could not be obtained. Without it, this format cannot be installed.",
        .errBundleUnreadable: "There is no .apk to install inside the bundle.",

        .deviceSection: "Where to install it",
        .deviceScanning: "Looking for devices…",
        .deviceRefresh: "Look again",
        .deviceNoneTitle: "No device found",
        .deviceNoneBody: "Plug in an Android phone with USB debugging turned on, or start one of the emulators below.",
        .deviceUnauthorized: "accept debugging on its screen",
        .deviceOffline: "not responding",
        .deviceEmulator: "emulator",
        .devicePhone: "phone",
        .deviceAndroidVersion: "Android %@",
        .emulatorSection: "Emulators",
        .emulatorStart: "Start",
        .emulatorStarting: "Starting…",
        .emulatorNone: "No emulator has been created. You create them with the Android SDK.",
        .emulatorHint: "It takes a minute or two to show up above, in the device list.",

        .abiMismatchTitle: "It will not install",
        .abiMismatchBody: "The app ships code for %@ and this device runs %@. Android will reject it.",
        .sdkTooOldTitle: "The device is too old",
        .sdkTooOldBody: "The app needs Android %@ and the device has Android %@.",
        .missingAdbTitle: "adb is missing",
        .missingAdbBody: "macOS cannot talk to an Android device on its own. adb is the bridge: it takes a few megabytes and installs once.",
        .androidCardTitle: "The bridge to Android",
        .androidCardBody: "adb talks to the phone over the cable, or to the emulator. This app touches nothing else on the device: it only installs, opens and uninstalls what you ask for.",
        .androidDisclaimer: "Installing outside Google Play skips its checks: only add .apk files whose origin you know. The package is installed as it is, unmodified.",
        .chooseApkFirst: "Choose an .apk app",
        .readyToInstall: "Ready to install",
        .missingAdbShort: "adb is missing",
        .noDeviceShort: "No device connected",
        .apkInstalledOn: "Installed on %@",

        .orientationSection: "Screen posture",
        .orientationAuto: "Automatic",
        .orientationPortrait: "Upright",
        .orientationLandscape: "Sideways",
        .orientationFree: "does not fix one",
        .orientationDeclared: "The .apk asks for %@.",
        .orientationRuntimeWarning: "Its manifest fixes none. Many games decide on startup, from their own code: if it comes out rotated, use the switch.",

        .emulatorSetUp: "Set up the emulator",
        .emulatorSettingUp: "Setting up the emulator…",
        .emulatorSetUpTitle: "The Android emulator is missing",
        .emulatorSetUpBody: "Opening an .apk on the Mac needs an Android inside it. The app can set that up on its own: it downloads the SDK, the system image for your chip, and creates the emulator.",
        .emulatorSetUpSize: "It takes about 6 GB and a good while; 8 GB must be free. Right now you have %@.",
        .emulatorNoSpace: "There is not enough room on the disk. The emulator needs about 6 GB free and there is %@.",
        .emulatorReady: "Emulator ready. You can run an .apk now.",
        .runApk: "Run",
        .runningApk: "Running…",
        .openAgain: "Open again",

        .logRotated: "Screen set to %@.",
        .logEmulatorReady: "The emulator has finished starting.",
        .statusApkRunning: "Opening the app",
        .errEmulatorTimeout: "The emulator took too long to start. Look at its window: it may be asking for something, or short on memory.",
        .errEmulatorSetUpFailed: "The emulator could not be set up completely. Check the activity; the script can be run again without repeating what is done.",
        .errEmulatorScriptMissing: "The script that sets up the emulator is missing. Reinstall the app with: bash scripts/install.sh",

        .recentsTitle: "Opened recently",
        .recentsClear: "Empty the list",
        .recentsReopen: "Open it again",
        .recentsRename: "Change the name",
        .recentsRenameHint: "The extension is kept",
        .recentsMove: "Move to another folder…",
        .recentsForget: "Take off the list",
        .recentsMissing: "no longer where it was",
        .errRenameEmpty: "Type a name.",
        .errNameTaken: "There is already a file called “%@” in that folder. Yours was left alone.",
        .errRenameFailed: "It did not work: %@",
        .errRecentMissing: "“%@” is no longer where it was. It must have been moved or deleted from outside.",
        .logRenamed: "It is called %@ now",
        .logMoved: "Moved to %@",

        .androidHelpTitle: "How to install an Android app",
        .androidHelpBody: "An .apk does not run inside the Mac the way an .exe does: it installs onto an Android device. There are two ways to have one.",
        .androidHelpFootnote: "The emulator and the SDK take several gigabytes and need Java. If you have an Android phone around, plugging it in is much quicker.",
        .androidOptionPhone: "A phone on the cable",
        .androidOptionPhoneWhy: "The quickest route. On the phone: Developer options → USB debugging. Plug it in and accept the prompt. Only adb is needed.",
        .androidOptionEmulator: "An emulator",
        .androidOptionEmulatorWhy: "No phone needed. Install the command-line tools, download a system image and create the emulator.",
        .androidOptionStudio: "Android Studio",
        .androidOptionStudioWhy: "If you are going to develop for Android anyway: it brings the SDK, the emulator and the device manager in one package.",

        .wineHelpTitle: "How to get Wine",
        .wineHelpBody: "Copy one of these commands and paste it into Terminal. When it finishes, come back here and press “Look for tools again”.",
        .wineHelpFootnote: "Wine does not come with macOS and cannot be bundled inside this app: it is a separate, large program that you install once. After that the app finds it by itself.",
        .copyCommand: "Copy command",
        .close: "Close",
        .findWineOnMac: "Find Wine on the Mac",
        .wineOptionGptk: "Game Porting Toolkit",
        .wineOptionGptkWhy: "Free. The build the community maintains for Apple silicon Macs.",
        .wineOptionCrossover: "CrossOver",
        .wineOptionCrossoverWhy: "Paid, with a 14-day trial. By far the most reliable one.",
        .wineOptionExisting: "I already have one",
        .wineOptionExistingWhy: "If Wine is already on your Mac, point at it with “Other Wine”.",

        .logProgramChosen: "Program chosen: %@",
        .logArchiveChosen: "Archive chosen: %@",
        .logDestination: "Destination: %@",
        .logToolsFound: "Tools: %@",
        .logNoTools: "No tools were found.",
        .logExtracting: "Extracting %@ with %@…",
        .logExtractedTo: "Done. The contents are in %@",
        .logOriginalKept: "The original file was not touched.",
        .logStopped: "Extraction stopped. What was already extracted stays in the folder.",
        .logStopping: "Stopping…",
        .logRetryingWith: "%@ could not handle this file. Trying with %@…",
        .logFirstRun: "First run: creating the Windows environment. This can take a couple of minutes.",
        .logWindowsReady: "Windows environment ready.",
        .logProgramClosed: "The program closed.",
        .logWineChosen: "Wine chosen manually: %@",
        .logCommandCopied: "Command copied. Paste it into Terminal.",
        .logActivityCopied: "Activity copied to the clipboard.",
        .logExtractorsPresent: "The extractors are already installed.",
        .logInstalling: "Installing with Homebrew: %@",
        .logInstallTakesTime: "This usually takes a couple of minutes.",
        .logInstallDone: "Installation finished.",
        .logWindowsReset: "Windows environment deleted. It will be created again the next time you run something.",
        .logWineUnblocked: "Wine unblocked. Windows programs can run now.",
        .logApkChosen: "App chosen: %@",
        .logDevicesFound: "Devices: %@",
        .logNoDevices: "No device is connected.",
        .logInstallingApk: "Installing %@ on %@…",
        .logApkInstalled: "Installed. It is on the device now.",
        .logApkLaunched: "Opening the app on the device…",
        .logApkUninstalled: "Uninstalled from the device.",
        .logEmulatorStarting: "Starting the “%@” emulator. It takes a couple of minutes.",

        .errNotAProgram: "“%@” is not a Windows program. Only .exe and .msi are accepted.",
        .errNotAnArchive: "“%@” is not an archive. Accepted formats include .rar, .zip and .7z.",
        .errUnknownFile: "“%@” is not recognised. It accepts .exe, .msi and archives such as .rar or .zip.",
        .errNoWine: "No Wine available. Install it or point at it manually.",
        .errNoExtractor: "No extractor is installed. Press “Install”.",
        .errPickProgram: "Choose a valid .exe or .msi program.",
        .errPickArchive: "Choose a valid archive.",
        .errPickDestination: "Choose a destination folder.",
        .errCannotCreateFolder: "Could not create the folder “%@”: %@",
        .errWineBlocked: "macOS has Wine blocked because it was marked as downloaded from the internet. Press “Unblock Wine” and try again.",
        .errNoRosetta: "Rosetta 2 is missing, and Wine needs it on Apple silicon Macs. Install it with: softwareupdate --install-rosetta",
        .errWinePrefixFailed: "This Wine cannot create the Windows environment. It usually happens with WineHQ versions that no longer work on macOS. Try another one from “Other Wine”.",
        .errUnblockFailed: "Wine could not be unblocked. From Terminal: xattr -dr com.apple.quarantine \"%@\"",
        .errNotWineExecutable: "There is no Wine executable there. Look for the “wine” file or a “Wine….app”.",
        .errProgramExit: "The program finished with code %@. Many Windows programs do not work under Wine: the ones needing drivers, anti-cheat or special graphics usually fail.",
        .errExtractExit2: "No extractor could open this archive. If it has a password, type it above; if it is split into parts, keep them all in the same folder.",
        .errExtractExit1: "The extraction finished with warnings. Check the activity: some file may have been skipped.",
        .errExtractExitOther: "The extractor finished with code %@. Check the activity to see why.",
        .errBusy: "Wait until the program that is running finishes.",
        .errHomebrewMissing: "Homebrew is not installed. Install it from brew.sh and try again.",
        .errInstallFailed: "Homebrew finished with code %@. Check the activity to see why.",
        .errNotAnApk: "“%@” is not an Android app. Accepted: .apk, .xapk, .apks and .aab.",
        .errNoAdb: "There is no adb. Install it to talk to the device.",
        .errNoDevice: "There is no device to install it on. Plug in a phone or start an emulator.",
        .errPickApk: "Choose a valid .apk file.",
        .errDeviceUnauthorized: "The phone is plugged in but has not authorised this Mac. Unlock it and accept the USB debugging prompt.",
        .errInstallNoAbis: "Android rejected the app: it ships code for a different processor than the device has.",
        .errInstallOldSdk: "Android rejected the app: it needs a newer version of Android than the device has.",
        .errInstallSignature: "Another version of this app, signed by someone else, is already there. Uninstall that one before putting this one on.",
        .errInstallDowngrade: "The device has a newer version of this app. Android does not allow going back a version without uninstalling the current one.",
        .errInstallNoSpace: "There is no room left on the device.",
        .errInstallNotSigned: "The .apk is not signed. Android does not install unsigned packages.",
        .errInstallBlocked: "The device blocked the install. Many phones need “Install via USB” turned on in Developer options, or a confirmation on screen.",
        .errInstallOther: "Android rejected the app: %@",
        .errNoLauncher: "It installed, but this app has no screen of its own to open. That is normal for services and add-ons.",

        .statusFinished: "Finished",
        .statusStopped: "Stopped",
        .statusExtracted: "Extracted",
        .statusFailed: "Finished with errors",
        .statusCannotStart: "Could not start",
        .statusExtracting: "Extracting %@",
        .statusRunning: "Running %@",
        .statusInstalling: "Installing",
        .statusToolsInstalled: "Extractors installed",
        .statusWindowsReset: "Windows reset",
        .statusWineUnblocked: "Wine unblocked",
        .statusPreparing: "Preparing Windows",
        .statusWindowsFailed: "Could not prepare Windows",
        .statusInstallingApk: "Installing %@",
        .statusApkInstalled: "Installed",
        .statusApkUninstalled: "Uninstalled",
        .statusScanning: "Looking for devices",
        .statusEmulatorStarting: "Starting the emulator"
    ]
}
